### ISSUE TITLE
route53 CNAME for deployment to prod

### ISSUE THREAD

**Issue by creedr** [DylanAllen/noiiice#13]
Hi, maybe I'm missing something here about route53 or routing in general, but when running `sls deploy --stage prod` with a `secrets.json` similar to 
```
"prod": {
    "region": "us-east-1",
    "blogCommentsDB": "NoiiceCommentsProd",
    "blogPostDB": "NoiiceBlogPostsProd",
    "userPool": "NoiiceBlogProd",
    "adminUser": "adminuser",
    "adminUserEmail": "admin@domain.com",
    "mediaBucket": "noiicemediaprod",
    "domain": "example.com",
    "certificateArn":"arn:aws:acm:us-east-1:randomnumber:certificate/randomguid",
    "restrictedStrings": "bad,words",
    "endpointType": "EDGE",
    "googleAnalyticsID": ""
    "certVerificationData": {
      "Name": "randomcertname.example.com.",
      "Type": "CNAME",
      "Value": "randomacmstuff.acm-validations.aws."
    },
    "sesTxtRecord": "randomTxtRecordstuff",
    "cloudFrontCNAME": {
      "Name": "example.com",
      "Type": "CNAME",
      "Value": "randomCloudFrontString.cloudfront.net"
    }
  }
```
Note that the cloudFrontCNAME was inserted during the deploy process, and the CNAME didn't seem to automatically deploy to Route53.

When trying to manually add the cloudFrontCNAME data to Route53 I will get an error message like 
```
[RRSet of type CNAME with DNS name example.com. is not permitted at apex in zone example.com.]
```

How do we add this CNAME data with the "naked domain" so that users can simply navigate to "https://example.com" to visit the website?

Everything worked fine with `--stage dev` and a CNAME like `dev.example.com`

**Comment by creedr** [comment]
Well, I may have solved my problem above...
Rather than trying to add a CNAME record, I added an A record with an Alias to the `randomCloudFrontString.cloudfront.net` url and now I can navigate to my site with teh naked domain.

However, one follow up question to this is:
The deploy process seems to make a cloudfront web distribution, but this cloudfront distribution doesn't show up in my AWS console. Any idea why not?

**Comment by DylanAllen** [comment]
Hi creedr,

You are right, for a root domain you will have to use an alias rather than a CNAME, and my automated deployment does not currently support that, but manually adding the alias in Route53 as you did is the way to do it.

The CloudFront distribution does not show up in the  CoudFront console because it is generated by API Gateway. You can find it in API Gateway > Custom Domain Names. The website is being served by a lambda function through API Gateway, so it isn't a standard CloudFront distribution.

Further info on the API Gateway Domain, if you were to deploy to a region other than us-east-1, you would not have a CloudFront url because other regions do not support EDGE endpoints.
