### ISSUE TITLE
Cannot find module '../../secrets.json'

### ISSUE THREAD

**Issue by creedr** [DylanAllen/noiiice#3]
Interesting project! I found it on twitter a few days ago.
I'm trying to get it up and running on Windows 10. 

When running the command
`sls createCert --stage dev`
I am getting an error...
`Error: Cannot find module '../../secrets.json'`

I did follow the instructions to rename `example-secrets.json` to `secrets.json`, and I am trying to run the `sls createCert` command in the `noiiice` directory.  I also tried copying the `secrets.json` file 2 directories back, and it still gives the same error.

Any ideas?

**Comment by DylanAllen** [comment]
I am able to run that command from Windows and Mac, so I don't expect that it is a Windows issue. Make sure that your `secrets.json` file is named correctly and in the root directory of your project. The command is looking at `../../secrets.json` because it is being run from `.serverless_plugins/noiiice-plugin/index.js` 

I just pushed some updates to the createCert function (not related to your issue) but you should pull those updates to make sure you don't encounter the bug that I just fixed.

Post your full error log, as well as  the version of node and Serverless you are running. 
`node --version`
`serverless --version`

**Comment by creedr** [comment]
> Make sure that your `secrets.json` file is named correctly

Well don't I feel silly.  I spent longer than I care to admit trying to figure out how to get that command to work with my file named `sectrets.json`

Full disclosure though, I'm running with 

node -v
v11.9.0

and 
serverless -v
Framework Core: 1.52.2
Plugin: 3.0.0
SDK: 2.1.1

In your [Install Noiiice](https://noiiice.com/post/install) you appear to be using an alias `sls` for `the `serverless` commands.  Took me a minute to figure that out too as this is my first usage of the `serverless` framework as well.

**Comment by DylanAllen** [comment]
Glad you figured it out! And that is a good point on the sls == serverless bit. I should make that documentation consistent and/or explain that shortcut for those new to the serverless framework.
